### PR TITLE
Refactor (ci): Update .github/workflows/build.yml code

### PR DESCRIPTION
**Pull request by joeltimothyoh**

### CODE REVIEW

**Comment by joeltimothyoh** [comment]
lgtm

**Comment by joeltimothyoh** [comment]
At least it would be maintainable but potential forkers of the repository, unlike having a dependency on code in and experience with PowerShell. @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh i don't mean to use an external templator. if templating is not necessary at all, as in this repo, then simply hardcoding the values will be sufficient in the build job.

**Comment by joeltimothyoh** [comment]
Matrices again are for the populating build environments with the necessary variable values for building however number of variants at scale. @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh matrices is simply a templator. 

to me, the `Dockerfile` should be completely self-contained (no `ARG`s). The other ci job options not pertaining to `docker build` command, are ci variables, and for ci logic it's beter to use a script  (e.g. `./build/build.sh` that can also be used outside the ci runner.

**Comment by joeltimothyoh** [comment]
I say it depends on use case. Pertaining to this project and it being OSS on GitHub, it suffices to use matrices with GHA.

This isn’t to say no improvements need to be made. I agree variables should be explicitly declared and abstractions done away with where possible. @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh for a simple repos with so few variants, it's better to make self-contained `Dockerfile`, and there is no need for matrices in github workflows to keep things simple.

**Comment by joeltimothyoh** [comment]
Opened https://github.com/startersclan/docker-steamcmd/issues/7

**Pull request merged**
